### ISSUE TITLE
Array of Double match method fails

### ISSUE THREAD

**Issue by brbrindle** [LabVIEW-DCAF/UIModules#14]
![image](https://cloud.githubusercontent.com/assets/20828732/23072714/f59ef954-f4ef-11e6-9915-930afbc61214.png)

in Labview 2015, the coerce to range doesn't seem to work for array double data types. probably others, but did not test. Data types that do have an explicit case work.

Was able to resolve issue by explicitly putting a case for data type.

**Comment by pollockm** [comment]
This looks like the data type matches (not strict) vi in the runtime class.

Looks like that was supposed to be "I8".."Extended Complex with Unit", Timestamp.  Instead it omitted the ".." and had a "," instead.

Also: that method should not have parentheses in the name.  This violates standard coding conventions.
