### ISSUE TITLE
No configuration validation for control names

### ISSUE THREAD

**Issue by tannerblair** [LabVIEW-DCAF/UIModules#15]
The UI Ref Module will let you enter an invalid control name, which results in an error being thrown in the engine.

**Comment by smithed** [comment]
I can't remember the specific behavior but it probably should lock you out only if the selected UI exists. If it doesn't exist (like its being built separately) you'd want to allow the configuring person to add custom control names.

**Comment by becega** [comment]
IMplementing what is discussed in #27 it will solve this issue.
